### ISSUE TITLE
Fix jruby-9.0.5.0 build with default gemset

### ISSUE THREAD

**Issue by bethesque** [pact-foundation/pact-ruby#121]
Unfortunately, this cannot be replicated when running the single spec on its own. Yay.

```
Failures:

  1) Pact::Provider::PactSpecRunner#run with multiple interactions and interactions_replay_order option set to random randomised interactions within consumer contract
     Failure/Error: raise "No non-lib lines in stack" unless stack

     RuntimeError:
       No non-lib lines in stack
     # /usr/local/var/rbenv/versions/jruby-9.0.5.0/lib/ruby/gems/shared/gems/rspec-support-3.5.0/lib/rspec/support/caller_filter.rb:66:in `block in first_non_rspec_line'
     # org/jruby/RubyKernel.java:1287:in `loop'
     # /usr/local/var/rbenv/versions/jruby-9.0.5.0/lib/ruby/gems/shared/gems/rspec-support-3.5.0/lib/rspec/support/caller_filter.rb:64:in `first_non_rspec_line'
     # /usr/local/var/rbenv/versions/jruby-9.0.5.0/lib/ruby/gems/shared/gems/rspec-mocks-3.5.0/lib/rspec/mocks/proxy.rb:52:in `block in add_message_expectation'
     # org/jruby/RubyHash.java:1177:in `fetch'
     # /usr/local/var/rbenv/versions/jruby-9.0.5.0/lib/ruby/gems/shared/gems/rspec-mocks-3.5.0/lib/rspec/mocks/proxy.rb:52:in `add_message_expectation'
     # /usr/local/var/rbenv/versions/jruby-9.0.5.0/lib/ruby/gems/shared/gems/rspec-mocks-3.5.0/lib/rspec/mocks/any_instance/expectation_chain.rb:30:in `create_message_expectation_on'
     # /usr/local/var/rbenv/versions/jruby-9.0.5.0/lib/ruby/gems/shared/gems/rspec-mocks-3.5.0/lib/rspec/mocks/any_instance/chain.rb:53:in `playback!'
     # /usr/local/var/rbenv/versions/jruby-9.0.5.0/lib/ruby/gems/shared/gems/rspec-mocks-3.5.0/lib/rspec/mocks/any_instance/message_chains.rb:67:in `block in playback!'
     # org/jruby/RubyArray.java:1560:in `each'
     # /usr/local/var/rbenv/versions/jruby-9.0.5.0/lib/ruby/gems/shared/gems/rspec-mocks-3.5.0/lib/rspec/mocks/any_instance/message_chains.rb:66:in `playback!'
     # /usr/local/var/rbenv/versions/jruby-9.0.5.0/lib/ruby/gems/shared/gems/rspec-mocks-3.5.0/lib/rspec/mocks/any_instance/recorder.rb:106:in `playback!'
     # /usr/local/var/rbenv/versions/jruby-9.0.5.0/lib/ruby/gems/shared/gems/rspec-mocks-3.5.0/lib/rspec/mocks/any_instance/recorder.rb:256:in `block in shuffle'
     # org/jruby/RubyMethod.java:127:in `call'
     # /usr/local/var/rbenv/versions/jruby-9.0.5.0/lib/ruby/gems/shared/gems/rspec-mocks-3.5.0/lib/rspec/mocks/message_expectation.rb:99:in `block in and_call_original'
     # org/jruby/RubyProc.java:318:in `call'
     # /usr/local/var/rbenv/versions/jruby-9.0.5.0/lib/ruby/gems/shared/gems/rspec-mocks-3.5.0/lib/rspec/mocks/message_expectation.rb:729:in `call'
     # /usr/local/var/rbenv/versions/jruby-9.0.5.0/lib/ruby/gems/shared/gems/rspec-mocks-3.5.0/lib/rspec/mocks/message_expectation.rb:565:in `invoke_incrementing_actual_calls_by'
     # /usr/local/var/rbenv/versions/jruby-9.0.5.0/lib/ruby/gems/shared/gems/rspec-mocks-3.5.0/lib/rspec/mocks/message_expectation.rb:422:in `invoke'
     # /usr/local/var/rbenv/versions/jruby-9.0.5.0/lib/ruby/gems/shared/gems/rspec-mocks-3.5.0/lib/rspec/mocks/proxy.rb:182:in `message_received'
     # /usr/local/var/rbenv/versions/jruby-9.0.5.0/lib/ruby/gems/shared/gems/rspec-mocks-3.5.0/lib/rspec/mocks/proxy.rb:326:in `message_received'
     # /usr/local/var/rbenv/versions/jruby-9.0.5.0/lib/ruby/gems/shared/gems/rspec-mocks-3.5.0/lib/rspec/mocks/method_double.rb:77:in `proxy_method_invoked'
     # /usr/local/var/rbenv/versions/jruby-9.0.5.0/lib/ruby/gems/shared/gems/rspec-mocks-3.5.0/lib/rspec/mocks/method_double.rb:64:in `block in define_proxy_method'
     # /usr/local/var/rbenv/versions/jruby-9.0.5.0/lib/ruby/gems/shared/gems/rspec-mocks-3.5.0/lib/rspec/mocks/any_instance/recorder.rb:257:in `block in shuffle'
     # org/jruby/RubyMethod.java:127:in `call'
     # /usr/local/var/rbenv/versions/jruby-9.0.5.0/lib/ruby/gems/shared/gems/rspec-mocks-3.5.0/lib/rspec/mocks/message_expectation.rb:99:in `block in and_call_original'
     # org/jruby/RubyProc.java:318:in `call'
     # /usr/local/var/rbenv/versions/jruby-9.0.5.0/lib/ruby/gems/shared/gems/rspec-mocks-3.5.0/lib/rspec/mocks/message_expectation.rb:729:in `call'
     # /usr/local/var/rbenv/versions/jruby-9.0.5.0/lib/ruby/gems/shared/gems/rspec-mocks-3.5.0/lib/rspec/mocks/message_expectation.rb:565:in `invoke_incrementing_actual_calls_by'
     # /usr/local/var/rbenv/versions/jruby-9.0.5.0/lib/ruby/gems/shared/gems/rspec-mocks-3.5.0/lib/rspec/mocks/message_expectation.rb:422:in `invoke'
     # /usr/local/var/rbenv/versions/jruby-9.0.5.0/lib/ruby/gems/shared/gems/rspec-mocks-3.5.0/lib/rspec/mocks/proxy.rb:182:in `message_received'
     # /usr/local/var/rbenv/versions/jruby-9.0.5.0/lib/ruby/gems/shared/gems/rspec-mocks-3.5.0/lib/rspec/mocks/proxy.rb:326:in `message_received'
     # /usr/local/var/rbenv/versions/jruby-9.0.5.0/lib/ruby/gems/shared/gems/rspec-mocks-3.5.0/lib/rspec/mocks/method_double.rb:77:in `proxy_method_invoked'
     # /usr/local/var/rbenv/versions/jruby-9.0.5.0/lib/ruby/gems/shared/gems/rspec-mocks-3.5.0/lib/rspec/mocks/method_double.rb:64:in `block in define_proxy_method'
     # /usr/local/var/rbenv/versions/jruby-9.0.5.0/lib/ruby/gems/shared/gems/rspec-mocks-3.5.0/lib/rspec/mocks/any_instance/recorder.rb:257:in `block in shuffle'
     # org/jruby/RubyMethod.java:127:in `call'
     # /usr/local/var/rbenv/versions/jruby-9.0.5.0/lib/ruby/gems/shared/gems/rspec-mocks-3.5.0/lib/rspec/mocks/message_expectation.rb:99:in `block in and_call_original'
     # org/jruby/RubyProc.java:318:in `call'
     # /usr/local/var/rbenv/versions/jruby-9.0.5.0/lib/ruby/gems/shared/gems/rspec-mocks-3.5.0/lib/rspec/mocks/message_expectation.rb:729:in `call'
     # /usr/local/var/rbenv/versions/jruby-9.0.5.0/lib/ruby/gems/shared/gems/rspec-mocks-3.5.0/lib/rspec/mocks/message_expectation.rb:565:in `invoke_incrementing_actual_calls_by'
     # /usr/local/var/rbenv/versions/jruby-9.0.5.0/lib/ruby/gems/shared/gems/rspec-mocks-3.5.0/lib/rspec/mocks/message_expectation.rb:422:in `invoke'
     # /usr/local/var/rbenv/versions/jruby-9.0.5.0/lib/ruby/gems/shared/gems/rspec-mocks-3.5.0/lib/rspec/mocks/proxy.rb:182:in `message_received'
     # /usr/local/var/rbenv/versions/jruby-9.0.5.0/lib/ruby/gems/shared/gems/rspec-mocks-3.5.0/lib/rspec/mocks/proxy.rb:326:in `message_received'
     # /usr/local/var/rbenv/versions/jruby-9.0.5.0/lib/ruby/gems/shared/gems/rspec-mocks-3.5.0/lib/rspec/mocks/method_double.rb:77:in `proxy_method_invoked'
     # /usr/local/var/rbenv/versions/jruby-9.0.5.0/lib/ruby/gems/shared/gems/rspec-mocks-3.5.0/lib/rspec/mocks/method_double.rb:64:in `block in define_proxy_method'
     # /usr/local/var/rbenv/versions/jruby-9.0.5.0/lib/ruby/gems/shared/gems/rspec-mocks-3.5.0/lib/rspec/mocks/any_instance/recorder.rb:257:in `block in shuffle'
     # org/jruby/RubyMethod.java:127:in `call'
     # /usr/local/var/rbenv/versions/jruby-9.0.5.0/lib/ruby/gems/shared/gems/rspec-mocks-3.5.0/lib/rspec/mocks/message_expectation.rb:99:in `block in and_call_original'
     # org/jruby/RubyProc.java:318:in `call'
     # /usr/local/var/rbenv/versions/jruby-9.0.5.0/lib/ruby/gems/shared/gems/rspec-mocks-3.5.0/lib/rspec/mocks/message_expectation.rb:729:in `call'
     # /usr/local/var/rbenv/versions/jruby-9.0.5.0/lib/ruby/gems/shared/gems/rspec-mocks-3.5.0/lib/rspec/mocks/message_expectation.rb:565:in `invoke_incrementing_actual_calls_by'
     # /usr/local/var/rbenv/versions/jruby-9.0.5.0/lib/ruby/gems/shared/gems/rspec-mocks-3.5.0/lib/rspec/mocks/message_expectation.rb:422:in `invoke'
     # /usr/local/var/rbenv/versions/jruby-9.0.5.0/lib/ruby/gems/shared/gems/rspec-mocks-3.5.0/lib/rspec/mocks/proxy.rb:182:in `message_received'
     # /usr/local/var/rbenv/versions/jruby-9.0.5.0/lib/ruby/gems/shared/gems/rspec-mocks-3.5.0/lib/rspec/mocks/proxy.rb:326:in `message_received'
     # /usr/local/var/rbenv/versions/jruby-9.0.5.0/lib/ruby/gems/shared/gems/rspec-mocks-3.5.0/lib/rspec/mocks/method_double.rb:77:in `proxy_method_invoked'
     # /usr/local/var/rbenv/versions/jruby-9.0.5.0/lib/ruby/gems/shared/gems/rspec-mocks-3.5.0/lib/rspec/mocks/method_double.rb:64:in `block in define_proxy_method'
     # /usr/local/var/rbenv/versions/jruby-9.0.5.0/lib/ruby/gems/shared/gems/rspec-mocks-3.5.0/lib/rspec/mocks/any_instance/recorder.rb:257:in `block in shuffle'
     # org/jruby/RubyMethod.java:127:in `call'
     # /usr/local/var/rbenv/versions/jruby-9.0.5.0/lib/ruby/gems/shared/gems/rspec-mocks-3.5.0/lib/rspec/mocks/message_expectation.rb:99:in `block in and_call_original'
     # org/jruby/RubyProc.java:318:in `call'
     # /usr/local/var/rbenv/versions/jruby-9.0.5.0/lib/ruby/gems/shared/gems/rspec-mocks-3.5.0/lib/rspec/mocks/message_expectation.rb:729:in `call'
     # /usr/local/var/rbenv/versions/jruby-9.0.5.0/lib/ruby/gems/shared/gems/rspec-mocks-3.5.0/lib/rspec/mocks/message_expectation.rb:565:in `invoke_incrementing_actual_calls_by'
     # /usr/local/var/rbenv/versions/jruby-9.0.5.0/lib/ruby/gems/shared/gems/rspec-mocks-3.5.0/lib/rspec/mocks/message_expectation.rb:422:in `invoke'
     # /usr/local/var/rbenv/versions/jruby-9.0.5.0/lib/ruby/gems/shared/gems/rspec-mocks-3.5.0/lib/rspec/mocks/proxy.rb:182:in `message_received'
     # /usr/local/var/rbenv/versions/jruby-9.0.5.0/lib/ruby/gems/shared/gems/rspec-mocks-3.5.0/lib/rspec/mocks/proxy.rb:326:in `message_received'
     # /usr/local/var/rbenv/versions/jruby-9.0.5.0/lib/ruby/gems/shared/gems/rspec-mocks-3.5.0/lib/rspec/mocks/method_double.rb:77:in `proxy_method_invoked'
     # /usr/local/var/rbenv/versions/jruby-9.0.5.0/lib/ruby/gems/shared/gems/rspec-mocks-3.5.0/lib/rspec/mocks/method_double.rb:64:in `block in define_proxy_method'
     # /usr/local/var/rbenv/versions/jruby-9.0.5.0/lib/ruby/gems/shared/gems/rspec-mocks-3.5.0/lib/rspec/mocks/any_instance/recorder.rb:257:in `block in shuffle'
     # org/jruby/RubyMethod.java:127:in `call'
     # /usr/local/var/rbenv/versions/jruby-9.0.5.0/lib/ruby/gems/shared/gems/rspec-mocks-3.5.0/lib/rspec/mocks/message_expectation.rb:99:in `block in and_call_original'
     # org/jruby/RubyProc.java:318:in `call'
     # /usr/local/var/rbenv/versions/jruby-9.0.5.0/lib/ruby/gems/shared/gems/rspec-mocks-3.5.0/lib/rspec/mocks/message_expectation.rb:729:in `call'
     # /usr/local/var/rbenv/versions/jruby-9.0.5.0/lib/ruby/gems/shared/gems/rspec-mocks-3.5.0/lib/rspec/mocks/message_expectation.rb:565:in `invoke_incrementing_actual_calls_by'
     # /usr/local/var/rbenv/versions/jruby-9.0.5.0/lib/ruby/gems/shared/gems/rspec-mocks-3.5.0/lib/rspec/mocks/message_expectation.rb:422:in `invoke'
     # /usr/local/var/rbenv/versions/jruby-9.0.5.0/lib/ruby/gems/shared/gems/rspec-mocks-3.5.0/lib/rspec/mocks/proxy.rb:182:in `message_received'
     # /usr/local/var/rbenv/versions/jruby-9.0.5.0/lib/ruby/gems/shared/gems/rspec-mocks-3.5.0/lib/rspec/mocks/proxy.rb:326:in `message_received'
     # /usr/local/var/rbenv/versions/jruby-9.0.5.0/lib/ruby/gems/shared/gems/rspec-mocks-3.5.0/lib/rspec/mocks/method_double.rb:77:in `proxy_method_invoked'
     # /usr/local/var/rbenv/versions/jruby-9.0.5.0/lib/ruby/gems/shared/gems/rspec-mocks-3.5.0/lib/rspec/mocks/method_double.rb:64:in `block in define_proxy_method'
     # /usr/local/var/rbenv/versions/jruby-9.0.5.0/lib/ruby/gems/shared/gems/rspec-mocks-3.5.0/lib/rspec/mocks/any_instance/recorder.rb:257:in `block in shuffle'
     # org/jruby/RubyMethod.java:127:in `call'
     # /usr/local/var/rbenv/versions/jruby-9.0.5.0/lib/ruby/gems/shared/gems/rspec-mocks-3.5.0/lib/rspec/mocks/message_expectation.rb:99:in `block in and_call_original'
     # org/jruby/RubyProc.java:318:in `call'
     # /usr/local/var/rbenv/versions/jruby-9.0.5.0/lib/ruby/gems/shared/gems/rspec-mocks-3.5.0/lib/rspec/mocks/message_expectation.rb:729:in `call'
     # /usr/local/var/rbenv/versions/jruby-9.0.5.0/lib/ruby/gems/shared/gems/rspec-mocks-3.5.0/lib/rspec/mocks/message_expectation.rb:565:in `invoke_incrementing_actual_calls_by'
     # /usr/local/var/rbenv/versions/jruby-9.0.5.0/lib/ruby/gems/shared/gems/rspec-mocks-3.5.0/lib/rspec/mocks/message_expectation.rb:422:in `invoke'
     # /usr/local/var/rbenv/versions/jruby-9.0.5.0/lib/ruby/gems/shared/gems/rspec-mocks-3.5.0/lib/rspec/mocks/proxy.rb:182:in `message_received'
     # /usr/local/var/rbenv/versions/jruby-9.0.5.0/lib/ruby/gems/shared/gems/rspec-mocks-3.5.0/lib/rspec/mocks/proxy.rb:326:in `message_received'
     # /usr/local/var/rbenv/versions/jruby-9.0.5.0/lib/ruby/gems/shared/gems/rspec-mocks-3.5.0/lib/rspec/mocks/method_double.rb:77:in `proxy_method_invoked'
     # /usr/local/var/rbenv/versions/jruby-9.0.5.0/lib/ruby/gems/shared/gems/rspec-mocks-3.5.0/lib/rspec/mocks/method_double.rb:64:in `block in define_proxy_method'
     # /usr/local/var/rbenv/versions/jruby-9.0.5.0/lib/ruby/gems/shared/gems/rspec-mocks-3.5.0/lib/rspec/mocks/any_instance/recorder.rb:257:in `block in shuffle'
     # org/jruby/RubyMethod.java:127:in `call'
     # /usr/local/var/rbenv/versions/jruby-9.0.5.0/lib/ruby/gems/shared/gems/rspec-mocks-3.5.0/lib/rspec/mocks/message_expectation.rb:99:in `block in and_call_original'
     # org/jruby/RubyProc.java:318:in `call'
     # /usr/local/var/rbenv/versions/jruby-9.0.5.0/lib/ruby/gems/shared/gems/rspec-mocks-3.5.0/lib/rspec/mocks/message_expectation.rb:729:in `call'
     # /usr/local/var/rbenv/versions/jruby-9.0.5.0/lib/ruby/gems/shared/gems/rspec-mocks-3.5.0/lib/rspec/mocks/message_expectation.rb:565:in `invoke_incrementing_actual_calls_by'
     # /usr/local/var/rbenv/versions/jruby-9.0.5.0/lib/ruby/gems/shared/gems/rspec-mocks-3.5.0/lib/rspec/mocks/message_expectation.rb:422:in `invoke'
     # /usr/local/var/rbenv/versions/jruby-9.0.5.0/lib/ruby/gems/shared/gems/rspec-mocks-3.5.0/lib/rspec/mocks/proxy.rb:182:in `message_received'
     # /usr/local/var/rbenv/versions/jruby-9.0.5.0/lib/ruby/gems/shared/gems/rspec-mocks-3.5.0/lib/rspec/mocks/proxy.rb:326:in `message_received'
     # /usr/local/var/rbenv/versions/jruby-9.0.5.0/lib/ruby/gems/shared/gems/rspec-mocks-3.5.0/lib/rspec/mocks/method_double.rb:77:in `proxy_method_invoked'
     # /usr/local/var/rbenv/versions/jruby-9.0.5.0/lib/ruby/gems/shared/gems/rspec-mocks-3.5.0/lib/rspec/mocks/method_double.rb:64:in `block in define_proxy_method'
     # /usr/local/var/rbenv/versions/jruby-9.0.5.0/lib/ruby/gems/shared/gems/rspec-mocks-3.5.0/lib/rspec/mocks/any_instance/recorder.rb:257:in `block in shuffle'
     # org/jruby/RubyMethod.java:127:in `call'
     # /usr/local/var/rbenv/versions/jruby-9.0.5.0/lib/ruby/gems/shared/gems/rspec-mocks-3.5.0/lib/rspec/mocks/message_expectation.rb:99:in `block in and_call_original'
     # org/jruby/RubyProc.java:318:in `call'
     # /usr/local/var/rbenv/versions/jruby-9.0.5.0/lib/ruby/gems/shared/gems/rspec-mocks-3.5.0/lib/rspec/mocks/message_expectation.rb:729:in `call'
     # /usr/local/var/rbenv/versions/jruby-9.0.5.0/lib/ruby/gems/shared/gems/rspec-mocks-3.5.0/lib/rspec/mocks/message_expectation.rb:565:in `invoke_incrementing_actual_calls_by'
     # /usr/local/var/rbenv/versions/jruby-9.0.5.0/lib/ruby/gems/shared/gems/rspec-mocks-3.5.0/lib/rspec/mocks/message_expectation.rb:422:in `invoke'
     # /usr/local/var/rbenv/versions/jruby-9.0.5.0/lib/ruby/gems/shared/gems/rspec-mocks-3.5.0/lib/rspec/mocks/proxy.rb:182:in `message_received'
     # /usr/local/var/rbenv/versions/jruby-9.0.5.0/lib/ruby/gems/shared/gems/rspec-mocks-3.5.0/lib/rspec/mocks/proxy.rb:326:in `message_received'
     # /usr/local/var/rbenv/versions/jruby-9.0.5.0/lib/ruby/gems/shared/gems/rspec-mocks-3.5.0/lib/rspec/mocks/method_double.rb:77:in `proxy_method_invoked'
     # /usr/local/var/rbenv/versions/jruby-9.0.5.0/lib/ruby/gems/shared/gems/rspec-mocks-3.5.0/lib/rspec/mocks/method_double.rb:64:in `block in define_proxy_method'
     # /usr/local/var/rbenv/versions/jruby-9.0.5.0/lib/ruby/gems/shared/gems/rspec-mocks-3.5.0/lib/rspec/mocks/any_instance/recorder.rb:257:in `block in shuffle'
     # org/jruby/RubyMethod.java:127:in `call'
     # /usr/local/var/rbenv/versions/jruby-9.0.5.0/lib/ruby/gems/shared/gems/rspec-mocks-3.5.0/lib/rspec/mocks/message_expectation.rb:99:in `block in and_call_original'
     # org/jruby/RubyProc.java:318:in `call'
     # /usr/local/var/rbenv/versions/jruby-9.0.5.0/lib/ruby/gems/shared/gems/rspec-mocks-3.5.0/lib/rspec/mocks/message_expectation.rb:729:in `call'
     # /usr/local/var/rbenv/versions/jruby-9.0.5.0/lib/ruby/gems/shared/gems/rspec-mocks-3.5.0/lib/rspec/mocks/message_expectation.rb:565:in `invoke_incrementing_actual_calls_by'
     # /usr/local/var/rbenv/versions/jruby-9.0.5.0/lib/ruby/gems/shared/gems/rspec-mocks-3.5.0/lib/rspec/mocks/message_expectation.rb:422:in `invoke'
     # /usr/local/var/rbenv/versions/jruby-9.0.5.0/lib/ruby/gems/shared/gems/rspec-mocks-3.5.0/lib/rspec/mocks/proxy.rb:182:in `message_received'
     # /usr/local/var/rbenv/versions/jruby-9.0.5.0/lib/ruby/gems/shared/gems/rspec-mocks-3.5.0/lib/rspec/mocks/proxy.rb:326:in `message_received'
     # /usr/local/var/rbenv/versions/jruby-9.0.5.0/lib/ruby/gems/shared/gems/rspec-mocks-3.5.0/lib/rspec/mocks/method_double.rb:77:in `proxy_method_invoked'
     # /usr/local/var/rbenv/versions/jruby-9.0.5.0/lib/ruby/gems/shared/gems/rspec-mocks-3.5.0/lib/rspec/mocks/method_double.rb:64:in `block in define_proxy_method'
     # /usr/local/var/rbenv/versions/jruby-9.0.5.0/lib/ruby/gems/shared/gems/rspec-mocks-3.5.0/lib/rspec/mocks/any_instance/recorder.rb:257:in `block in shuffle'
     # org/jruby/RubyMethod.java:127:in `call'
     # /usr/local/var/rbenv/versions/jruby-9.0.5.0/lib/ruby/gems/shared/gems/rspec-mocks-3.5.0/lib/rspec/mocks/message_expectation.rb:99:in `block in and_call_original'
     # org/jruby/RubyProc.java:318:in `call'
     # /usr/local/var/rbenv/versions/jruby-9.0.5.0/lib/ruby/gems/shared/gems/rspec-mocks-3.5.0/lib/rspec/mocks/message_expectation.rb:729:in `call'
     # /usr/local/var/rbenv/versions/jruby-9.0.5.0/lib/ruby/gems/shared/gems/rspec-mocks-3.5.0/lib/rspec/mocks/message_expectation.rb:565:in `invoke_incrementing_actual_calls_by'
     # /usr/local/var/rbenv/versions/jruby-9.0.5.0/lib/ruby/gems/shared/gems/rspec-mocks-3.5.0/lib/rspec/mocks/message_expectation.rb:422:in `invoke'
     # /usr/local/var/rbenv/versions/jruby-9.0.5.0/lib/ruby/gems/shared/gems/rspec-mocks-3.5.0/lib/rspec/mocks/proxy.rb:182:in `message_received'
     # /usr/local/var/rbenv/versions/jruby-9.0.5.0/lib/ruby/gems/shared/gems/rspec-mocks-3.5.0/lib/rspec/mocks/proxy.rb:326:in `message_received'
     # /usr/local/var/rbenv/versions/jruby-9.0.5.0/lib/ruby/gems/shared/gems/rspec-mocks-3.5.0/lib/rspec/mocks/method_double.rb:77:in `proxy_method_invoked'
     # /usr/local/var/rbenv/versions/jruby-9.0.5.0/lib/ruby/gems/shared/gems/rspec-mocks-3.5.0/lib/rspec/mocks/method_double.rb:64:in `block in define_proxy_method'
     # /usr/local/var/rbenv/versions/jruby-9.0.5.0/lib/ruby/gems/shared/gems/rspec-mocks-3.5.0/lib/rspec/mocks/any_instance/recorder.rb:257:in `block in shuffle'
     # org/jruby/RubyMethod.java:127:in `call'
     # /usr/local/var/rbenv/versions/jruby-9.0.5.0/lib/ruby/gems/shared/gems/rspec-mocks-3.5.0/lib/rspec/mocks/message_expectation.rb:99:in `block in and_call_original'
     # org/jruby/RubyProc.java:318:in `call'
     # /usr/local/var/rbenv/versions/jruby-9.0.5.0/lib/ruby/gems/shared/gems/rspec-mocks-3.5.0/lib/rspec/mocks/message_expectation.rb:729:in `call'
     # /usr/local/var/rbenv/versions/jruby-9.0.5.0/lib/ruby/gems/shared/gems/rspec-mocks-3.5.0/lib/rspec/mocks/message_expectation.rb:565:in `invoke_incrementing_actual_calls_by'
     # /usr/local/var/rbenv/versions/jruby-9.0.5.0/lib/ruby/gems/shared/gems/rspec-mocks-3.5.0/lib/rspec/mocks/message_expectation.rb:422:in `invoke'
     # /usr/local/var/rbenv/versions/jruby-9.0.5.0/lib/ruby/gems/shared/gems/rspec-mocks-3.5.0/lib/rspec/mocks/proxy.rb:182:in `message_received'
     # /usr/local/var/rbenv/versions/jruby-9.0.5.0/lib/ruby/gems/shared/gems/rspec-mocks-3.5.0/lib/rspec/mocks/proxy.rb:326:in `message_received'
     # /usr/local/var/rbenv/versions/jruby-9.0.5.0/lib/ruby/gems/shared/gems/rspec-mocks-3.5.0/lib/rspec/mocks/method_double.rb:77:in `proxy_method_invoked'
     # /usr/local/var/rbenv/versions/jruby-9.0.5.0/lib/ruby/gems/shared/gems/rspec-mocks-3.5.0/lib/rspec/mocks/method_double.rb:64:in `block in define_proxy_method'
     #
     #   Showing full backtrace because every line was filtered out.
     #   See docs for RSpec::Configuration#backtrace_exclusion_patterns and
     #   RSpec::Configuration#backtrace_inclusion_patterns for more information.

  2) Pact::Provider::PactSpecRunner#run with multiple interactions and interactions_replay_order option set to random does not change consumer interactions
     Failure/Error: consumer_contract["interactions"] = consumer_contract["interactions"].shuffle
       The message 'shuffle' was received by #<Array:52816 > but has already been received by [{"description"=>"Description 1", "provider_state"=>"there is an alligator named Mary", "request"=>{}, "response"=>{"status"=>200}}, {"description"=>"Description 2", "provider_state"=>"there is not an alligator named Mary", "request"=>{}, "response"=>{"status"=>200}}, {"description"=>"Description 1", "provider_state"=>"an error occurs retrieving an alligator", "request"=>{}, "response"=>{"status"=>500}}]
     # ./lib/pact/provider/pact_spec_runner.rb:132:in `ordered_pact_json'
     # ./lib/pact/provider/pact_spec_runner.rb:124:in `block in initialize_specs'
     # ./lib/pact/provider/pact_spec_runner.rb:120:in `initialize_specs'
     # ./lib/pact/provider/pact_spec_runner.rb:33:in `run'
     # ./spec/lib/pact/provider/pact_spec_runner_spec.rb:81:in `block in (root)'

Finished in 43.18 seconds (files took 9.7 seconds to load)
270 examples, 2 failures, 2 pending

Failed examples:

rspec  # Pact::Provider::PactSpecRunner#run with multiple interactions and interactions_replay_order option set to random randomised interactions within consumer contract
rspec  # Pact::Provider::PactSpecRunner#run with multiple interactions and interactions_replay_order option set to random does not change consumer interactions
```

**Comment by YOU54F** [comment]
jruby was dropped from our testing matrix many moons ago

https://github.com/pact-foundation/pact-ruby/commit/d46f712cd1029da28dee8e3d1cebb9cf0a3bce3e
