### ISSUE TITLE
Service Provider with honours_pacts_from_pact_broker - Error Undefined Method

### ISSUE THREAD

**Issue by rmzoni** [pact-foundation/pact-ruby#232]
Hi,

I'm trying to config a rails for pact provider project using a pact broker. I'm following this documentation here:  https://docs.pact.io/implementation_guides/ruby/verifying_pacts.

I had made this configurations:
- pact_helpers.rb
```ruby
require 'pact/provider/rspec'

pact_broker = ENV['PACT_BROKER'] || 'https://pact-broker.dev.foo.com'
provider_version = ENV['GIT_COMMIT'] || `git rev-parse --verify HEAD`
provider_branch = ENV['GIT_BRANCH'] || `git name-rev --name-only HEAD`
publish_flag = ENV['PUBLISH_VERIFICATION_RESULTS'] == 'true'

Pact.service_provider "scp" do
  # app_version provider_version
  # app_version_tags [provider_branch]
  # publish_verification_results publish_flag

  honours_pacts_from_pact_broker do
    # Base URL of pact broker is mandatory
    # basic auth username/password and token are optional parameters
    pact_broker_base_url pact_broker, {username: '...', password: '...', token: '...'}

    # Specify the consumer version tags for the pacts you want to verify
    # Simple config - a list of tag names
    # This will verify the latest pact with the tag `dev` and the latest pact with the tag `prod`
    consumer_version_tags ['dev', 'prod']

    # Advanced configuration - new syntax
    # This uses the new 'pacts for verification' API if is enabled in your broker
    # For more info on the API see
    #  https://docs.pact.io/pact_broker/advanced_topics/provider_verification_results#pacts-for-verification
    # For a full explanation of how selectors work, see
    #  https://docs.pact.io/pact_broker/advanced_topics/consumer_version_selectors
    # Requires pact gem version v1.56.0+
    #
    # tag: name of the tag (required)
    # latest: true|false. Defaults to false, but generally you want the latest pact, so set it to true. To verify all pacts for the specified tag, set latest: false, or omit the key.
    # fallback_tag: the name of the tag to use if a pact with the specified tag does not exist (optional)
    # consumer: the name of the consumer
    #consumer_version_selectors [
    #      { tag: 'main', latest: true },
    #      { tag: ENV['GIT_BRANCH'], fallback_tag: 'main', latest: true },
    #      { tag: 'prod', latest: true }
    #     ]


    enable_pending true
    include_wip_pacts_since "2020-01-01"
  end
end

```

- Rakefile
```ruby
# frozen_string_literal: true

# Add your own tasks in files placed in lib/tasks ending in .rake,
# for example lib/tasks/capistrano.rake, and they will automatically be available to Rake.

require 'pact/tasks'
require_relative 'config/application'


Rails.application.load_tasks
#task :default => 'pact:verify'
```
When I run: `rake pact:Verify`, Iḿ receiving this error here:
```
SPEC_OPTS='' /usr/share/rvm/rubies/ruby-2.6.3/bin/ruby -S pact verify --pact-helper /home/rafael_manzoni/wkp/servicing/spec/service_consumers/pact_helper.rb
Traceback (most recent call last):
        20: from /home/rafael_manzoni/.rvm/gems/ruby-2.6.3@servicing/bin/pact:23:in `<main>'
        19: from /home/rafael_manzoni/.rvm/gems/ruby-2.6.3@servicing/bin/pact:23:in `load'
        18: from /home/rafael_manzoni/.rvm/gems/ruby-2.6.3@servicing/gems/pact-1.9.6/bin/pact:4:in `<top (required)>'
        17: from /home/rafael_manzoni/.rvm/gems/ruby-2.6.3@servicing/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
        16: from /home/rafael_manzoni/.rvm/gems/ruby-2.6.3@servicing/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
        15: from /home/rafael_manzoni/.rvm/gems/ruby-2.6.3@servicing/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
        14: from /home/rafael_manzoni/.rvm/gems/ruby-2.6.3@servicing/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
        13: from /home/rafael_manzoni/.rvm/gems/ruby-2.6.3@servicing/gems/pact-1.9.6/lib/pact/cli.rb:22:in `verify'
        12: from /home/rafael_manzoni/.rvm/gems/ruby-2.6.3@servicing/gems/pact-1.9.6/lib/pact/cli/run_pact_verification.rb:14:in `call'
        11: from /home/rafael_manzoni/.rvm/gems/ruby-2.6.3@servicing/gems/pact-1.9.6/lib/pact/cli/run_pact_verification.rb:21:in `call'
        10: from /home/rafael_manzoni/.rvm/gems/ruby-2.6.3@servicing/gems/pact-1.9.6/lib/pact/cli/run_pact_verification.rb:43:in `load_pact_helper'
         9: from /home/rafael_manzoni/.rvm/gems/ruby-2.6.3@servicing/gems/pact-1.9.6/lib/pact/cli/run_pact_verification.rb:43:in `load'
         8: from /home/rafael_manzoni/wkp/servicing/spec/service_consumers/pact_helper.rb:8:in `<top (required)>'
         7: from /home/rafael_manzoni/.rvm/gems/ruby-2.6.3@servicing/gems/pact-1.9.6/lib/pact/provider/configuration/dsl.rb:9:in `service_provider'
         6: from /home/rafael_manzoni/.rvm/gems/ruby-2.6.3@servicing/gems/pact-support-0.5.9/lib/pact/shared/dsl.rb:65:in `build'
         5: from /home/rafael_manzoni/.rvm/gems/ruby-2.6.3@servicing/gems/pact-support-0.5.9/lib/pact/shared/dsl.rb:10:in `instance_eval_with_previous_context_available'
         4: from /home/rafael_manzoni/.rvm/gems/ruby-2.6.3@servicing/gems/pact-support-0.5.9/lib/pact/shared/dsl.rb:45:in `with_previous_context_available'
         3: from /home/rafael_manzoni/.rvm/gems/ruby-2.6.3@servicing/gems/pact-support-0.5.9/lib/pact/shared/dsl.rb:11:in `block in instance_eval_with_previous_context_available'
         2: from /home/rafael_manzoni/.rvm/gems/ruby-2.6.3@servicing/gems/pact-support-0.5.9/lib/pact/shared/dsl.rb:11:in `call'
         1: from /home/rafael_manzoni/wkp/servicing/spec/service_consumers/pact_helper.rb:13:in `block in <top (required)>'
/home/rafael_manzoni/.rvm/gems/ruby-2.6.3@servicing/gems/pact-support-0.5.9/lib/pact/shared/dsl.rb:21:in `method_missing': undefined method `honours_pacts_from_pact_broker' for main:Object (NoMethodError)

```

**Comment by bethesque** [comment]
You're using version 1.9.6 of the pact gem. The current version is 1.55.6. Please upgrade.
