### ISSUE TITLE
Unable to use provider tag in publish results

### ISSUE THREAD

**Issue by rmzoni** [pact-foundation/pact-ruby#233]
## Context
When I use the `app_version_tags` in provider verification results, I'm receiving  an error that contains a new line character in the response json.

- Config
```ruby
Pact.service_provider 'scp' do
  app_version provider_version
  app_version_tags [branch]
  publish_verification_results true

  honours_pacts_from_pact_broker do
    # Base URL of pact broker is mandatory
    # basic auth username/password and token are optional parameters
    pact_broker_base_url pact_broker
```

- Error
```
INFO: Tagging version c6c2de20e5e1f1b9d51259db1964fd20d786f6da
 of scp as "master"
Traceback (most recent call last):
        37: from /home/rafael_manzoni/.rvm/gems/ruby-2.6.3@servicing/bin/pact:23:in `<main>'
        36: from /home/rafael_manzoni/.rvm/gems/ruby-2.6.3@servicing/bin/pact:23:in `load'
        35: from /home/rafael_manzoni/.rvm/gems/ruby-2.6.3@servicing/gems/pact-1.55.7/bin/pact:4:in `<top (required)>'
        34: from /home/rafael_manzoni/.rvm/gems/ruby-2.6.3@servicing/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
        33: from /home/rafael_manzoni/.rvm/gems/ruby-2.6.3@servicing/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
        32: from /home/rafael_manzoni/.rvm/gems/ruby-2.6.3@servicing/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
        31: from /home/rafael_manzoni/.rvm/gems/ruby-2.6.3@servicing/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
        30: from /home/rafael_manzoni/.rvm/gems/ruby-2.6.3@servicing/gems/pact-1.55.7/lib/pact/cli.rb:31:in `verify'
        29: from /home/rafael_manzoni/.rvm/gems/ruby-2.6.3@servicing/gems/pact-1.55.7/lib/pact/cli/run_pact_verification.rb:13:in `call'
        28: from /home/rafael_manzoni/.rvm/gems/ruby-2.6.3@servicing/gems/pact-1.55.7/lib/pact/cli/run_pact_verification.rb:21:in `call'
        27: from /home/rafael_manzoni/.rvm/gems/ruby-2.6.3@servicing/gems/pact-1.55.7/lib/pact/cli/run_pact_verification.rb:53:in `run_specs'
        26: from /home/rafael_manzoni/.rvm/gems/ruby-2.6.3@servicing/gems/pact-1.55.7/lib/pact/cli/run_pact_verification.rb:76:in `run_with_configured_pacts_from_pact_helper'
        25: from /home/rafael_manzoni/.rvm/gems/ruby-2.6.3@servicing/gems/pact-1.55.7/lib/pact/provider/pact_spec_runner.rb:35:in `run'
        24: from /home/rafael_manzoni/.rvm/gems/ruby-2.6.3@servicing/gems/pact-1.55.7/lib/pact/provider/pact_spec_runner.rb:90:in `run_specs'
        23: from /home/rafael_manzoni/.rvm/gems/ruby-2.6.3@servicing/gems/rspec-core-3.9.3/lib/rspec/core/runner.rb:71:in `run'
        22: from /home/rafael_manzoni/.rvm/gems/ruby-2.6.3@servicing/gems/rspec-core-3.9.3/lib/rspec/core/runner.rb:89:in `run'
        21: from /home/rafael_manzoni/.rvm/gems/ruby-2.6.3@servicing/gems/rspec-core-3.9.3/lib/rspec/core/runner.rb:115:in `run_specs'
        20: from /home/rafael_manzoni/.rvm/gems/ruby-2.6.3@servicing/gems/rspec-core-3.9.3/lib/rspec/core/reporter.rb:76:in `report'
        19: from /home/rafael_manzoni/.rvm/gems/ruby-2.6.3@servicing/gems/rspec-core-3.9.3/lib/rspec/core/reporter.rb:174:in `finish'
        18: from /home/rafael_manzoni/.rvm/gems/ruby-2.6.3@servicing/gems/rspec-core-3.9.3/lib/rspec/core/reporter.rb:196:in `close_after'
        17: from /home/rafael_manzoni/.rvm/gems/ruby-2.6.3@servicing/gems/rspec-core-3.9.3/lib/rspec/core/reporter.rb:243:in `close'
        16: from /home/rafael_manzoni/.rvm/gems/ruby-2.6.3@servicing/gems/rspec-core-3.9.3/lib/rspec/core/reporter.rb:208:in `notify'
        15: from /home/rafael_manzoni/.rvm/gems/ruby-2.6.3@servicing/gems/rspec-core-3.9.3/lib/rspec/core/reporter.rb:208:in `each'
        14: from /home/rafael_manzoni/.rvm/gems/ruby-2.6.3@servicing/gems/rspec-core-3.9.3/lib/rspec/core/reporter.rb:209:in `block in notify'
        13: from /home/rafael_manzoni/.rvm/gems/ruby-2.6.3@servicing/gems/pact-1.55.7/lib/pact/provider/rspec/pact_broker_formatter.rb:28:in `close'
        12: from /home/rafael_manzoni/.rvm/gems/ruby-2.6.3@servicing/gems/pact-1.55.7/lib/pact/provider/verification_results/publish_all.rb:10:in `call'
        11: from /home/rafael_manzoni/.rvm/gems/ruby-2.6.3@servicing/gems/pact-1.55.7/lib/pact/provider/verification_results/publish_all.rb:19:in `call'
        10: from /home/rafael_manzoni/.rvm/gems/ruby-2.6.3@servicing/gems/pact-1.55.7/lib/pact/provider/verification_results/publish_all.rb:19:in `collect'
         9: from /home/rafael_manzoni/.rvm/gems/ruby-2.6.3@servicing/gems/pact-1.55.7/lib/pact/provider/verification_results/publish_all.rb:22:in `block in call'
         8: from /home/rafael_manzoni/.rvm/gems/ruby-2.6.3@servicing/gems/pact-1.55.7/lib/pact/provider/verification_results/publish.rb:21:in `call'
         7: from /home/rafael_manzoni/.rvm/gems/ruby-2.6.3@servicing/gems/pact-1.55.7/lib/pact/provider/verification_results/publish.rb:34:in `call'
         6: from /home/rafael_manzoni/.rvm/gems/ruby-2.6.3@servicing/gems/pact-1.55.7/lib/pact/provider/verification_results/publish.rb:68:in `tag_versions_if_configured'
         5: from /home/rafael_manzoni/.rvm/gems/ruby-2.6.3@servicing/gems/pact-1.55.7/lib/pact/provider/verification_results/publish.rb:80:in `tag_versions'
         4: from /home/rafael_manzoni/.rvm/gems/ruby-2.6.3@servicing/gems/pact-1.55.7/lib/pact/provider/verification_results/publish.rb:80:in `each'
         3: from /home/rafael_manzoni/.rvm/gems/ruby-2.6.3@servicing/gems/pact-1.55.7/lib/pact/provider/verification_results/publish.rb:84:in `block in tag_versions'
         2: from /home/rafael_manzoni/.rvm/gems/ruby-2.6.3@servicing/gems/pact-1.55.7/lib/pact/hal/http_client.rb:70:in `body'
         1: from /home/rafael_manzoni/.rvm/gems/ruby-2.6.3@servicing/gems/json-2.5.1/lib/json/common.rb:216:in `parse'
/home/rafael_manzoni/.rvm/gems/ruby-2.6.3@servicing/gems/json-2.5.1/lib/json/common.rb:216:in `parse': 809: unexpected token at 'URL path cannot contain a new line character.' (JSON::ParserError)
```

**Comment by bethesque** [comment]
If you're using a git command to get your branch name, you'll need to do a `.strip` on it to remove the new line character on the end. eg. 

```
`git name-rev --name-only HEAD`.strip
```

**Comment by rmzoni** [comment]
> If you're using a git command to get your branch name, you'll need to do a `.strip` on it to remove the new line character on the end. eg.
> 
> ```
> `git name-rev --name-only HEAD`.strip
> ```

Hi, I made this and for test purpose i fixed the tag. But, the problem persists.

**Comment by bethesque** [comment]
You're hitting this middleware so there must be a new line in there somewhere.

https://github.com/pact-foundation/pact_broker/blob/master/lib/rack/pact_broker/invalid_uri_protection.rb#L49

Try setting `verbose true` in the `honours_pacts_from_pact_broker` configuration. It will show you the HTTP output.

**Comment by rmzoni** [comment]
> You're hitting this middleware so there must be a new line in there somewhere.
> 
> https://github.com/pact-foundation/pact_broker/blob/master/lib/rack/pact_broker/invalid_uri_protection.rb#L49
> 
> Try setting `verbose true` in the `honours_pacts_from_pact_broker` configuration. It will show you the HTTP output.

Thanks for the response. But verbose configuration only log requests for the verification process.

The publish requests were not been logging. The error remains the same.

**Comment by bethesque** [comment]
Look at the log.

```
INFO: Tagging version c6c2de20e5e1f1b9d51259db1964fd20d786f6da
 of scp as "master"

```

There's a new line after the version number. It's showing in the log itself.

**Comment by rmzoni** [comment]
It really was the `/n` but in the provider version like you mentioned before. @bethesque thanks to be so helpful.

I think it would be nice to update the pact documentation to use strip:
https://docs.pact.io/implementation_guides/ruby/verifying_pacts#publishing-verification-results-to-a-pact-broker
```ruby
provider_version = (ENV['GIT_COMMIT'] || `git rev-parse --verify HEAD`).strip
provider_branch = (ENV['GIT_BRANCH'] || `git name-rev --name-only HEAD`).strip
```

**Comment by bethesque** [comment]
Done! https://docs.pact.io/implementation_guides/ruby/verifying_pacts#publishing-verification-results-to-a-pact-broker
